[theme]
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#374151"
font = "sans serif"

[server]
headless = true
port = $PORT
enableCORS = false

[browser]
gatherUsageStats = false